FROM ruby:<%= Arkenstone::RUBY_VERSION %>

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev
RUN apt-get install -y nodejs

ENV APP_DIR /app
RUN mkdir $APP_DIR
WORKDIR $APP_DIR

ADD Gemfile* $APP_HOME/
RUN bundle install

ADD . $APP_HOME