---
- name: Install PostgreSQL
  become: yes
  apt: name=postgresql state=present

- name: Install psycopg2 module
  become: yes
  pip: name=psycopg2 state=present
  
- name: Create PostgreSQL user
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_user: name=vagrant role_attr_flags=CREATEDB,CREATEROLE,SUPERUSER
